// app states
export const MAIN_MENU_STATE = 'MAIN_MENU';
export const SETTINGS_MENU_STATE = 'SETTINGS_MENU';
export const SPEED_SETTINGS_MENU_STATE = 'SPEED_SETTINGS_MENU';
export const LEFT_EYE_COLOR_PICKER_MENU_STATE = 'LEFT_EYE_COLOR_PICKER_MENU';
export const RIGHT_EYE_COLOR_PICKER_MENU_STATE = 'RIGHT_EYE_COLOR_PICKER_MENU';
export const ABOUT_INFO_STATE = 'ABOUT_INFO';
export const LEFT_EYE_COLOR_SETTINGS_INFO_STATE = 'LEFT_EYE_COLOR_SETTINGS_INFO';
export const RIGHT_EYE_COLOR_SETTINGS_INFO_STATE = 'RIGHT_EYE_COLOR_SETTINGS_INFO';
export const BOARD_SIZE_SETTINGS_STATE = 'BOARD_SIZE_SETTINGS_MENU';
export const BLOCKS_STATE = 'BLOCKS';

// blocks game states
export const BLOCKS_GAME_INITIAL = 'BLOCKS_GAME_INITIAL';
export const BLOCKS_GAME_PLAYING = 'BLOCKS_GAME_PLAYING';
export const BLOCKS_GAME_PAUSE = 'BLOCKS_GAME_PAUSE';
