export const MAIN_MENU_STATE = 'MAIN_MENU';
export const SETTINGS_MENU_STATE = 'SETTINGS_MENU';
export const SPEED_SETTINGS_MENU_STATE = 'SPEED_SETTINGS_MENU';
export const LEFT_EYE_COLOR_PICKER_MENU_STATE = 'LEFT_EYE_COLORPICKER_MENU_STATE';
export const RIGHT_EYE_COLOR_PICKER_MENU_STATE = 'RIGHT_EYE_COLORPICKER_MENU_STATE';
